version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_CONFIG_EXTRA:
        define( 'WP_DEBUG', true );
    volumes:
      - ./:/var/www/html/wp-content/plugins/woocommerce-payment-gateway

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    #restart: always
    ports:
      - '9997:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
  